export const Card11=[
{id:1,
      Category: "Shirt ",
      Price: 1299,
      Quantity:"2",
    },
    {id:2,
      Category: "Pants ",
      Price: 1499,
      Quantity:"12",
    },
    {id:3,
      Category: "Jackets ",
      Price: 2999,
      Quantity:"14",
    },
    {id:4,
      Category: "Shorts ",
      Price: 999,
      Quantity:"12",
    },
    {id:5,
      Category: "Shoes ",
      Price: 1999,
      Quantity:"22",
    },
    {id:6,
      Category: "Caps ",
      Price: 499,
      Quantity:"8",
    },
    {id:7,
      Category: "Belts ",
      Price: 799,
      Quantity:"18",
    },
    {id:8,
      Category: "T-Shirts ",
      Price: 999,
      Quantity:"14",
    }
]

